name: personal_notes
description: Personal Notes
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.24.0
  flutter_modular: ^5.0.3
  animations: ^2.0.5
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  firebase_auth: ^3.11.1
  google_sign_in: ^5.4.2
  unicons: ^2.1.0
  cloud_firestore: ^3.5.0

flutter:
  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700