name: personal_notes
description: Personal Notes
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.4.1
  flutter_modular: ^5.0.3
  animations: ^2.0.5
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  firebase_auth: ^4.2.5
  google_sign_in: ^5.4.2
  unicons: ^2.1.0
  cloud_firestore: ^4.3.1
  hive: ^2.2.3
  path_provider: ^2.0.11
  uuid: ^3.0.6
  shimmer: ^2.0.0
  dartz: ^0.10.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700